user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /users
    defaults:
        _format: json
